#!/usr/bin/env bash
# Output : The subdomain [SUBDOMAIN] is a [RECORD_TYPE] and points to [DESTINATION]
# When only the parameter domain is passed, information for all subdomains is printed out.
# When both a domain and subdomain are passed, information for the specified domain is printed.
# Usage: ./0-world_wide_web [DOMAIN] [optional SUBDOMAIN]

get_domain() {


    record=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s", $4}')
    ip=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s", $5}')
    printf "The subdomain %s is a %s record and points to %s\n" "$2" "$record" "$ip" 

}



if [ -z "$2" ]; then
    for sub in "www" "lb-01" "web-01" "web-02"
    do
	get_domain "$1" "$sub"
    done
else
    get_domain "$1" "$2"
fi
