#!/usr/bin/env bash
# This script prints "Best school" 10 times, and "Hi" on 9th iteration
n=1

while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n == 9 ]
    then
        echo "Hi"
    fi
    (( n++ ))
done
