#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 100.25.168.56
    User ubuntu
    passwordAuthentification no
    IdentityFile ~/.ssh/school
